### ISSUE TITLE
.NET CLI tool not working on Mac

### ISSUE THREAD

**Issue by TheTravellingSalesman** [ZoeyZolotova/mm-rando#117]
# Versions
MMR v1.11.0.7
.NET v3.1.201

# Error description

I've been attempting to create a randomized run on my Mac using the CLI tool and have run into a series of issues (the last of which has halted progress entirely). I'll list them out in order to try to enhance the tool. 👍 

1) After running `dotnet MMR.CLI.dll` on a fresh install, I got:
```
>>> dotnet MMR.CLI.dll

Default settings file not found. Generating...
Generated settings.json. Edit it to set your settings.
Invalid custom item list.
```

I don't imagine the default item list is deliberately invalid. I cross-examined it with the `settings.json` on my Windows machine, and found that there were three fields missing:
```
...,
"CustomItemListString": "------------",
"CustomStartingItemListString": "--",
"CustomJunkLocationsString": "------------",
...
```

2) After fixing that, I got the following:
```
>>> dotnet MMR.CLI.dll

Error building ROM: The type initializer for 'Gdip' threw an exception.

Please contact the development team and provide them more information
```

If there's a higher debugging level that I have access to you'd like me to run, I'd be happy to help! Unfortunately there isn't much more in way of logs that I can pass on at the moment.

**Comment by ZoeyZolotova** [comment]
These have already been fixed for the next release, thanks.
For now, you can work-around the 2nd issue by installing libc6-dev and libgdiplus. In the next version, we'll be changing to use a different imaging library.

**Comment by TheTravellingSalesman** [comment]
libc6-dev does not appear to exist for Unix? I've only been able to find it for Ubuntu and Debian.

**Comment by alkaris2** [comment]
Same compatibility issue on Linux, but also it tries to look for `hostfxr.dll` which it can't find in the .NET SDK. If this is suppose to be self-contained app, it should be done with either the following;

```
dotnet publish -r linux-x64 --self-contained true -c release
dotnet publish -r macos --self-contained true -c release
dotnet publish -r win10-x64 --self-contained true -c release
```

to then not have to require the application to download and install the .NET package, it can become isolated from other .NET apps, and app doesn't have to use locally installed shared runtime if available.
