### ISSUE TITLE
Suggestion: Change title deed icons to distinct unique icons instead of palette swaps

### ISSUE THREAD

**Issue by Apprehentice** [ZoeyZolotova/mm-rando#120]
Currently, title deed icons are different colored variants of the same icon. While this makes sense from a ROM size perspective, this makes the game less accessible to color-blind individuals as they cannot distinguish, at a glance, which deed is which, as color-sighted people can. I propose that each deed have its own icon with some symbolic distinction from one-another.

**Comment by ZoeyZolotova** [comment]
You can use a texture pack for this. And your OS may come with color blind settings. Windows 10 does.
