### ISSUE TITLE
Garo mask locked in stone tower death armos puzzle, ikana inaccessible

### ISSUE THREAD

**Issue by Willburd** [ZoeyZolotova/mm-rando#128]
Version: 1.12.0.11
Settings: {"AddStrayFairies":true,"AddSkulltulaTokens":false,"UpdateShopAppearance":true,"SpeedupLabFish":false,"UserLogicFileName":"","UseCustomItemList":false,"CloseCows":true,"ArrowCycling":true,"CritWiggleDisable":true,"DrawHash":true,"FastPush":true,"UpdateWorldModels":true,"OcarinaUnderwater":true,"QuestItemStorage":true,"LogicMode":"Casual","EnabledTricks":[],"AddSongs":true,"AddDungeonItems":true,"AddShopItems":true,"AddMoonItems":false,"AddFairyRewards":true,"AddOther":true,"AddNutChest":false,"CrazyStartingItems":true,"AddCowMilk":false,"AddMundaneRewards":false,"RandomizeBottleCatchContents":false,"ExcludeSongOfSoaring":true,"RandomizeDungeonEntrances":false,"RandomizeEnemies":false,"NoStartingItems":false,"CustomItemListString":"------------","CustomStartingItemListString":"--","CustomJunkLocationsString":"------------","DamageMode":"Default","DamageEffect":"Default","MovementMode":"Default","FloorType":"Default","ClockSpeed":"Default","HideClock":false,"BlastMaskCooldown":"Short","EnableSunsSong":false,"AllowFierceDeityAnywhere":false,"ByoAmmo":false,"DeathMoonCrash":false,"ShortenCutscenes":false,"QuickTextEnabled":false,"Character":"LinkMM","GossipHintStyle":"Relevant","FreeHints":true,"ClearHints":false,"PreventDowngrades":true,"UpdateChests":true,"FixEponaSword":true,"SpeedupBeavers":false,"SpeedupDampe":false,"SpeedupDogRace":false,"SpeedupBank":false}
Seed: 556386693

Ikana could not be accessed without Garo mask, but the mask is locked inside stone tower (Death armos maze chest).

**Comment by Willburd** [comment]
Just a potential thought on it... Does the randomizer take the one way path from Ikana river to the swamp as one way?

**Comment by ZoeyZolotova** [comment]
You can access Ikana using the Gibdo mask, which is normal behavior.
