### ISSUE TITLE
Short emulator freeze on Dolphin's Virtual Console when going through doors using "Vanilla Layout"

### ISSUE THREAD

**Issue by Admentus64** [ZoeyZolotova/mm-rando#133]
There is a freeze issue on the Virtual Console (Dolphin emulator) when going through a door. This lasts a second or so. Using the CPU Clock Override through Dolphin diminishes the time needed for the emulator to continue again, but... It's not ideal. It's not an issue on Project64 through. It seems the game freezes the Dolphin emulator to do some calculations before being able to continue once again, which the Virtual Console can not seem to handle very effectively, hence, the delay / freeze / pause.

The bug does not affect doors within dungeons, but does affect for example the doors in the Great Bay Skulltula House, but only once (when re-entering) since the map stays loaded in the ROM or something. Doors that change the scene will keep causing the delay / freeze every single time.

This issue only occurs when the "Vanilla Layout" is chosen as the Mode/Logic since MM Rando v1.12.0.10. So that means using "Vanilla Layout" on MM Rando v1.11.0.7 is fine. The updates after v1.12.0.10 are still broken as I tested MM Rando v1.12.1.0 in the "Vanilla Layout". I don't get why, but "Vanilla Layout" changes something the Virtual Console does not like, while the other options like "Casual" still work perfectly as they should when opening doors. You can test the issue with any door in Clock Town (such as the Treasure Chest Shop).

Somehow MM Rando did something differently since v1.12.0.10. I do not know if it's the way how doors are being handled or how the scene itself being loaded. The weird thing is, changing the scene by anything other than a door does NOT cause a freeze, like traversing through the different parts of Clock Town.

The Redux project for Majora's Mask (https://github.com/MarocZan/Majora-s-Mask-REDUX) is based on v1.12 of the Randomizer, which means Redux inherits the issue as well.

**Comment by Admentus64** [comment]
Apparently this issue got fixed since MM-Randomizer v1.13.0.11, the next release after the "broken" MM-Randomizer v1.12.1.0 release.

I am curious to know which PR or commit addressed this issue :)

**Comment by ZoeyZolotova** [comment]
It was probably related to this fix in 1.13.0.11
> Fixed crash that can occur when loading a room while some item models are still rendering.
