### ISSUE TITLE
Fierce Deity Mask Removed from Inventory After Trading all 20 masks with the 4 Kids on The Moon and talking to the kid with Majora's Mask. WTF!?

### ISSUE THREAD

**Issue by 03bgood** [ZoeyZolotova/mm-rando#134]
Okay so when you give all the masks to the kids on the moon and the kid wearing the Majora's Mask gives you a randomized item (Piece of Heart), it seems to remove the Fierce Deity Mask for whatever reason when I played the Song of Time inside the room where you fight Majora and upon resetting via SoT to Day 1, it was gone from my mask inventory! The other 23 masks were still in my inventory but the Fierce Deity Mask was not. I went back to the randomized location where I got the mask, but unfortunately, I only got a blue rupee this time. I'm playing an older seed of this, so it might've been fixed in later releases.

**Comment by ZoeyZolotova** [comment]
You're using an outdated version of the Randomizer. This has been fixed.
