### ISSUE TITLE
Spoiler logs possible to recreate after ROM generation

### ISSUE THREAD

**Issue by Kjelli** [ZoeyZolotova/mm-rando#14]
Why is this an issue?

Problem:
As someone on Discord observed, when doing a race you get a fixed settings string that the participants use. Races do not allow spoiler logs being generated. At the time being, this **is possible** by simply generating a new ROM with the identical settings string, with spoiler logs enabled.

Proposed solution:
* The seeding mechanism should be handled differently if the spoiler log generation is toggled on. It should still be deterministic (same rom for each seed+settings).
* The new way of handling seeding should preferably not be possible to reverse-engineer (e.g. don't add x to the original seed, makes it possible to subtract from original seed x to generate correct spoiler log).

**Comment by ZoeyZolotova** [comment]
Fixed in 1.5.0 with patching feature.
