### ISSUE TITLE
Suggestion - more casual keysanity

### ISSUE THREAD

**Issue by ZeteCx** [ZoeyZolotova/mm-rando#140]
It was most likely suggested before but an option to randomize dungeon items with everything else but keys wont disappear from your inventory when you play the song of time (like the fairy sanity option).
It will be great to be able to play keysanity without the need to physically write down where every key is.
I am aware its kinda changing the whole game idea, but we are playing a weird rom hack of it, we kinda already changing the game already.
i would like to try keysanity, because without it every dungeon barely have any items in it - its all dungeon items and they are barely worth visiting while casually playing because most of the stuff are in the overworld.
It will be a pretty nice option to pick that dungeon items wont reset with the other items while playing song of time while having keysanity on.

**Comment by SlickYoshi** [comment]
The devs have expressed disinterest in doing so in the past. It's not just simply "changing the game", but rather taking away part of the core mechanic. Fairies and Skulltula tokens had to be changed to make sure logic could properly accommodate them. If keys were added to the permanent items list, dungeon logic would need to be entirely reworked to account for worst possible key usage, both with and without tricks. It would be an incredible amount of work for essentially no payoff, as you can just simply skip almost all of the keys anyway, if you have the items necessary.

**Comment by ZoeyZolotova** [comment]
This will be part of 1.15. There'll be an option for keys to stay with you after you song of time, and used keys will return to your inventory to avoid affecting logic.
