### ISSUE TITLE
60fps or 30fps Mod

### ISSUE THREAD

**Issue by jet082** [ZoeyZolotova/mm-rando#142]
It is possible to mod Majora's Mask to run in 60fps. Although this produces some minor issues (mostly that item animations do not run at 60fps), it would be a nice option since the game really does look so much better at either 30 or 60fps.

I do not know enough to tell you how to patch the file per-say, but the following will give you the ability to find the value you need to change:

1) Open Project64 and enable the debugger (enable advanced settings first)
2) At the title screen, search for an 8-bit value that starts at 1 (you will need to increase the max results considerably)
3) When in-game, search these results for a value that changes to 3
4) Pause the game and see which of these values then changes to 2

Then, once you've identified some candidates (you may get between 3-10 results), go ahead and change them one-by-one to the value 1 and you can identify the fps mode variable. You will find that the game now runs at 60fps.

**Comment by ZoeyZolotova** [comment]
This seems more like a suggestion for modloader or something. I don't think it adds anything to the rando for this option to be worth the effort to implement. If someone does provide a fully functional patch for it though, it shouldn't take much effort to incorporate it into the rando.

**Comment by SillyPigii** [comment]
Tell Me I Want To Know How The Sigma Do I Run Majoras Mask On 60 FPS With Citra Emulator
