### ISSUE TITLE
Not enough magic beans

### ISSUE THREAD

**Issue by SVM78** [ZoeyZolotova/mm-rando#145]
According to my spoiler log, only 3 locations give out 1 bean each. However, the first door in the Ikana Well requires 5 beans. I had to use cheats to get through it. Bottlesanity also seems to have cause some issues, as Deku Princess was the only way to get Bugs, which I needed to get the boss key to get deku princess in the first place.

**Comment by ZoeyZolotova** [comment]
You can get infinite beans from the bean salesman in deku palace.

**Comment by ZoeyZolotova** [comment]
And you can scoop the deku princess multiple times by re-entering the room.
