### ISSUE TITLE
Game crash on "Vanilla Layout" when rolling into the tree outside Observatory.

### ISSUE THREAD

**Issue by kaneki-haise94** [ZoeyZolotova/mm-rando#149]
I've tested this with quite a few different seeds on vanilla layout (works perfectly on all other modes), but when you roll into the tree with the guy trying to get to two red rupees the game crashes. I'm not sure if it crashes on Dolphin or WiiVC as I've only tested it on Project64, ParaLLEI and MupenPlus. Running a playthrough on casual with no item randomizations on was an easy work around though.

https://user-images.githubusercontent.com/90798028/133500477-b83b4b41-afd7-4087-919d-d6079c60f68b.mp4

**Comment by ZoeyZolotova** [comment]
Hi, thanks for reporting this. I will fix it for the next release.

**Comment by ZoeyZolotova** [comment]
Fixed for 1.15
