### ISSUE TITLE
Most recent release isn't randomizing items

### ISSUE THREAD

**Issue by CLGZFGFrankerZ123** [ZoeyZolotova/mm-rando#150]
Visual and audio changes work fine, but all items are vanilla. Spoiler logs show no item information. Version 1.13.0.13 worked fine.

This is with casual logic. It is not vanilla settings.

**Comment by ZoeyZolotova** [comment]
You didn't randomize any items. This also isn't a place for support, go to the Majora's Mask Randomizer discord for support.
