### ISSUE TITLE
Doggy Racetrack crashes

### ISSUE THREAD

**Issue by aplumafreak500** [ZoeyZolotova/mm-rando#156]
Version: 1.13.0.13
Seed: 13865453
Settings:
```
{"UserLogicFileName":"","UseCustomItemList":false,"CloseCows":true,"ArrowCycling":true,"CritWiggleDisable":false,"DrawHash":true,"ElegySpeedup":true,"FastPush":true,"IceTrapQuirks":false,"UpdateWorldModels":true,"OcarinaUnderwater":false,"QuestItemStorage":true,"ContinuousDekuHopping":true,"UpdateShopAppearance":true,"ProgressiveUpgrades":true,"LogicMode":"Casual","EnabledTricks":[491,520,530,515,513],"AddSongs":true,"AddDungeonItems":true,"AddShopItems":true,"AddMoonItems":true,"AddFairyRewards":true,"AddOther":true,"AddNutChest":false,"CrazyStartingItems":true,"AddCowMilk":true,"AddSkulltulaTokens":true,"AddStrayFairies":true,"AddMundaneRewards":true,"RandomizeBottleCatchContents":false,"ExcludeSongOfSoaring":false,"RandomizeDungeonEntrances":false,"RandomizeEnemies":false,"NoStartingItems":true,"CustomItemListString":"------------","CustomStartingItemListString":"--","CustomJunkLocationsString":"------------","IceTraps":"None","IceTrapAppearance":"MajorItems","DamageMode":"Default","DamageEffect":"Default","MovementMode":"Default","FloorType":"Default","NutandStickDrops":"Default","ClockSpeed":"Default","HideClock":false,"BlastMaskCooldown":"Default","EnableSunsSong":false,"AllowFierceDeityAnywhere":true,"ByoAmmo":false,"DeathMoonCrash":false,"ShortenCutsceneSettings":{"General":"BlastMaskThief, BoatArchery, FishermanGame, MilkBarPerformance, HungryGoron, TatlInterrupts, EverythingElse","BossIntros":"Odolwa, Goht, Gyorg, Twinmold, Majora, Wart, IgosDuIkana, Gomess"},"QuickTextEnabled":false,"Character":"LinkMM","GossipHintStyle":"Default","FreeHints":false,"ClearHints":false,"PreventDowngrades":true,"UpdateChests":true,"FixEponaSword":true,"SpeedupBeavers":true,"SpeedupDampe":true,"SpeedupDogRace":true,"SpeedupLabFish":true,"SpeedupBank":true}
```

Anytime I pick up a dog in the Doggy Racetrack with the Mask of Truth (other than the gold dog) the game crashes. Also, after winning the race, the game crashes. In both cases, turning off TLB exceptions allowed the game to progress, displaying the last text box (which can result in a softlock depending on what that text box was), leading me to suspect the game is trying to load invalid message IDs for the dogs and for the dog lady.

Feel free to close if this doesn't affect MMR 1.14.x, but I am currently unable to test that version.

Edit: Attempting to leave the scene after winning the prize (via Soaring or simply exiting normally) also crashes even with TLB exceptions off. Song of Double Time is disabled, however. I'll let the game roll over to the next 6-hour increment to test that and then post another edit.

Edit 2: Apparently that scene does not trigger day transitions.

**Comment by aplumafreak500** [comment]
Confirmed that none of this happens in 1.15.0.11-beta. Closing for now.

**Comment by ZoeyZolotova** [comment]
Hey, thanks for reporting this. Someone else has also reported this and I have confirmed that it is a bug that occurs when the message table grows beyond its initial size. It can still occur in the latest beta. I will fix it for the next version.
