### ISSUE TITLE
Suggestion: Add options for the randomizer to check to make sure the game is 100% completable.

### ISSUE THREAD

**Issue by Lombardi128** [ZoeyZolotova/mm-rando#158]
Me and a friend have been playing through this randomizer for the first time, and it had been a blast. However, we noticed that a Heart Piece has been placed inside the pre-Clock Town Chest in the introduction section. I'm not skilled enough to glitch my way through the wall where the Happy Mask Salesman is, so this means that our current playthrough is not completable. Another hiccup we've hit is that the Special Delivery Mail was placed as the second bank reward. This means that we can only get one of the two items that we could get with that mail. I read somewhere that the randomizer makes sure to not lock any necessary items behind glitches, but I consider heart pieces to be necessary. They may not be needed to beat the game, but they are needed to complete the game. For me, it isn't a true Zelda experience unless I unlock and collect everything.

So I ask that an option be added that makes it so that the randomizer makes sure to place items in such a way so that all upgrades and important items can be obtained and all areas visited.

**Comment by OlafurKrH** [comment]
For the second bank reward, you can simply withdraw rupees to go under 500, then bring it back to 500 to get the mail again.

**Comment by Lombardi128** [comment]
This the second bank reward, so I assume going back under 1000 will work as well. While not the most elegant, I guess its good enough. That just leaves the pre-Clock Town Chest. From what I gather online, it would still be possible to glitch through with by using bombs to somehow glitch up and over the ceiling, but I just can't get it to work. I would really appreciate an option to check for completability, and have the randomizer make sure to not leave anything unobtainable.

**Comment by OlafurKrH** [comment]
oh. thats always the third for me because I randomize EVERYTHING except the glitched items, so the bank rewards are 200, 500 and 1000 for me. But yes, it does work. I also make sure to exclude that pre-CT chest, plus that out of bounds rupee in Deku Palace. I'm not sure if its then the vanilla reward or just some consumable junk, (as in, no HP) but not too sure.

**Comment by Lombardi128** [comment]
A better solution, then, would be to make it so that the pre-Clock Town Chest and out of bounds rupee are disabled by default. That way people like me who are unaware that they are in the pool won't get tricked.

**Comment by ZoeyZolotova** [comment]
It seems the core of the issue here is you consider Heart Pieces to be important, but the randomizer does not. You can also simply not randomize the category 'Glitches Required', which is off by default. If you enabled it without reading what you enabled, then that's a separate issue.
