### ISSUE TITLE
[Suggestion] Make the Song of Double Time ask for the exact hour to warp to (like MM3D)

### ISSUE THREAD

**Issue by ShadowOne333** [ZoeyZolotova/mm-rando#167]
Modify the text prompt that you get when playing the Song of Double Time to instead prompt a text box that asks for player input to specify the number of the hour the player wants to warp to. Probably the Clock Town Banker's text could be used as a good example for such a feature, where the player inputs the number of the hour instead of the rupees and after that, the time fast forwards to said hour.

I've found some documentation from the decompilation that might help to bring this up to MM 64:

- **_Song of Time effects C code_** from the MM decompilation. This would help to understand what the game does when calling the Song of Double Time with the Ocarina and how it modifies the time:
https://github.com/zeldaret/mm/blob/132dd6a373e84f97f60b45372bf3c9c90d92f2a6/src/overlays/actors/ovl_En_Test6/z_en_test6.c

- **_Clock Town Banker code (reference for the number-changing textbox)_**. This could help to make a new text/message ID based on the Clock Town Banker's textbox that asks for a specific hour/number that the player wants to warp to, and combined with the Song of Time effect code, it could potentially make it viable to make the player input a specific time of hour they want to travel to like in MM 3D (taking into account the current time so it only allows the player to input hours after the current one and not before, probably in 24-hour format could help; and also that in the Final Night it can't be used): 
https://github.com/zeldaret/mm/blob/aa87f0de89773875696ff9787e9128c2634b36f3/src/overlays/actors/ovl_En_Ginko_Man/z_en_ginko_man.c#L439-L451

- **_Pierre The Scarecrow overlay_**. This could help to make a selector between Night or next Day for the Song of Double Time, so you don't have to use the Song of Double Time to go from 6 to 6 hours, and could instead jump 6 to 12 hours if wanted. (This is in the dire case the feature of specifying the exact hour to move to won't work): 
https://github.com/zeldaret/mm/blob/bb96e47f8df9fa42e2120b7acda90432bacfde39/src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c

**Comment by ZoeyZolotova** [comment]
I appreciate the effort you've made to find documentation in the MM decompilation. However, it would be a lot of effort to implement this and we already have an option to enable the Sun's Song which already lets you advance to the hour you want. I'm going to close this issue for that reason, plus this isn't really the right place to make suggestions. Next time please go to the [Discord server's suggestions channel](https://discord.com/channels/547921289554296832/575629634209579008) and search for your suggestion (which has been made and responded to many times before) before posting it.
