### ISSUE TITLE
Issue: Keaton grass is extremely inconsistent, often gives only the first result.

### ISSUE THREAD

**Issue by Ekulsk** [ZoeyZolotova/mm-rando#169]
So, I was playing on a particular seed with keaton grass randomization enabled and trying the keaton grass checks, and it very commonly only gives the first result. Most notably with bombs but most methods seem to not give you everything you ought to get. I managed to get it to drop properly with magic spin attack... sometimes, but it's still very janky and gives a lot of duplicates

I tried this on a couple seeds and randomization strings, here's the setting string I most recently tested: -ffffc00-------------------b83----1f-e0000000---3ffff-fffffc00-400--30000020 

Now, maybe this isn't truly an issue, as long as the logic accounts for needing spin before you do keaton grass,

**Comment by ZoeyZolotova** [comment]
It's working as intended.
