### ISSUE TITLE
Suggestion: disable stylish jumps when hands are not empty

### ISSUE THREAD

**Issue by ez-me** [ZoeyZolotova/mm-rando#175]
This is mostly to help ZFG and others that don't like how the stylish jumps don't allow to jump slash and mess with where you are aiming with the bow.

Title says "when hands are not empty", which could include just Deku Sticks, Great Fairy Sword, Kokiri/Razor/Gilded Sword, and Fierce Deity Sword alongside the Bow (maybe Zora's punches as well); or just any item that remains in Link's hands (like bottles).

Alternatively if that's not possible or too hard, simply an option to disable them would be fine.

**Comment by ZoeyZolotova** [comment]
Thannks for the suggestion. Please post suggestions in the suggestions channel on Discord.
