### ISSUE TITLE
Unable to re-acquire Letter to Mama

### ISSUE THREAD

**Issue by SparroHawc** [ZoeyZolotova/mm-rando#177]
Letter was located in the Swamp Grotto near the climbable tree.  After acquiring it and using it to help ??? in the Stockpot Inn, the chest now only has a Recovery Heart upon resetting.

Using Project64.  Save file and spoiler log attached.
[ZELDA MAJORA'S MASK.zip](https://github.com/user-attachments/files/16478111/ZELDA.MAJORA.S.MASK.zip)
[MMR-1.16.0.12-2024-08-02T01-35-51.5938372Z_SpoilerLog.txt](https://github.com/user-attachments/files/16478113/MMR-1.16.0.12-2024-08-02T01-35-51.5938372Z_SpoilerLog.txt)

**Comment by ZoeyZolotova** [comment]
According to your spoiler log, the Letter to Mama is in the Near Swamp Spider House Grotto (the grotto in the poisoned swamp area near the Swamp Spider House), not in the Path to Swamp Grotto (the grotto near the climbable tree in Road to Southern Swamp).

Also I'd prefer in the future if you asked for help in the `support` channel in the Discord server.

**Comment by SparroHawc** [comment]
Well, shoot.  Should have checked that first, sorry.  Thought it was a genuine bug; instead it's just that the tracker I'm using isn't very detailed with its pinned locations.
