### ISSUE TITLE
[Issue] Ocarina of time + SoT + SoS won't randomize

### ISSUE THREAD

**Issue by SkySkiMe** [ZoeyZolotova/mm-rando#178]
As the title says, even when I select the options to randomize them I still start with them. I've made 3 different seeds with the options marked and yet I still start with them.

**Comment by ZoeyZolotova** [comment]
In the default settings, those are added as extra starting items. You need to remove them from that list if you don't want to start with them.

In the future please ask for support in the discord server's support channel.
