### ISSUE TITLE
Mikau only possible once.

### ISSUE THREAD

**Issue by OlafurKrH** [ZoeyZolotova/mm-rando#23]
So this seed, Mirror Shield came from Mikau. Later on, I found a Hylian Shield and downgraded (Seriously, when will this no longer be a thing?) I thought no problem, just get back there and heal him again. Nope, I pushed him to shore, the cutscene where he walked and fell didn't play (though he still did that) and when I played the song, nothing happened. I made a savestate just in case and left the area, came back and talked to him to hear his final message and the game softlocked.

Soooo yeah, probably best to forbid certain items from Mikau if it can't be fixed.

**Comment by ZoeyZolotova** [comment]
I just tried this and it seems to be working properly. Got Mirror Shield from Zora Mask check, then played Song of Time, then did Zora Mask check again and got Mirror Shield.

Can you provide any further information? Settings string and seed would be great. Item list if applicable. Spoiler log too if possible.

**Comment by OlafurKrH** [comment]
Oh! I tried it again and worked now. Maybe it only happened this way cause I was in the final 6 hours or I warped to Great Bay? I dunno, but maybe it was just a slight hiccup.

**Comment by ZoeyZolotova** [comment]
Alright that's good. Closing this issue then.

**Comment by OlafurKrH** [comment]
yeah, probably pushed him at a weird angle, sorry about that.
