### ISSUE TITLE
Item Priority Problem

### ISSUE THREAD

**Issue by deadb0t** [ZoeyZolotova/mm-rando#33]
There seems to be an issue where items have priority over each other.  For example, if you get the mirror shield, and then find the hero shield, you lose the mirror shield.  Same goes for the different sized wallets, and for the different sized bomb bags and arrow quivers.  This causes softlocks where you may not be able to get the item back.  Is there even a fix for this?

**Comment by ZoeyZolotova** [comment]
Progressive items are something we're looking at doing, but we don't have an active developer with the required ROM hacking expertise.

In the meantime, you can work around the problem by playing Song of Time and re-acquiring the upgrades from where you found them. No softlock.

**Comment by deadb0t** [comment]
Much Appreciated.  I was just trying that myself to make sure that it wasnt fully locked.  I noticed it also happens with the swords.
