### ISSUE TITLE
Current Crashs and Issues

### ISSUE THREAD

**Issue by mudkipslike** [ZoeyZolotova/mm-rando#49]
Known issues are
N64/Everdrive :  Goron Baby cutscene will crash.
P64 : Moon is completely black unless you change graphic plugins
Retroarch : Certain Drivers will crash on Cremia Cutscene with shortened cutscenes
Bizhawk : Certain Drivers will crash on Cremia Cutscene with shortened cutscenes

**Comment by moseythepirate** [comment]
The Cremia cutscene crashes on N64/Everdrive as well.

**Comment by Monkeor** [comment]
When entering the goron baby's room, it seems like the game tries to play a cutscene and softlocks. The first few times, it looked like it was trying to play the cutscene that plays after first beating Odolwa, but the latest time it looked like the cutscene for healing Darmani's ghost.

**Comment by ZoeyZolotova** [comment]
Goron Baby crash has been fixed for version 1.9
Cremia Cutscene issue with shortened cutscenes has been fixed for 1.9
PJ64 issue is a plugin issue and will not be fixed.
