### ISSUE TITLE
Randomizing some but not all bottle items seems to stop generation with no error

### ISSUE THREAD

**Issue by WillMoff** [ZoeyZolotova/mm-rando#50]
This custom item string 1fff-ffffffff-ffffffff-fff9f7ff-ff800003-ffffffff-ffffffe3-fffbffff
and this settings string 8in-1-
in version 1.5.0.3381

Title says it all.
Bug was reported by @Master Chief#7218  on the discord to (Mod) WillMoff
WillMoff replicated the issue and solved it by adding all of the bottle contents to the list of randomized items

**Comment by ZoeyZolotova** [comment]
Fixed in https://github.com/ZoeyZolotova/mm-rando/commit/e2a9698766e92a0c504f013a3c6a39ef3bc23f67
