### ISSUE TITLE
Deku Mask unobtainable?

### ISSUE THREAD

**Issue by Lcdscreen** [ZoeyZolotova/mm-rando#51]
Casual/Glitchless

 Item                                        Location
Deku Mask                                >> Bombers' Notebook

I may be mistaken, but since you need to be wearing the Deku Mask when you talk to Jim in order to typically receive the Bombers' Notebook, would this not make the Deku Mask unobtainable?

**Comment by ZoeyZolotova** [comment]
It's actually the opposite. If you talk to him as deku then you don't get the notebook.
