### ISSUE TITLE
Enemy Randomizer: Woodfall Temple Black Boes

### ISSUE THREAD

**Issue by aplumafreak500** [ZoeyZolotova/mm-rando#61]
If Enemy Randomizer is active, the dark room in the Woodfall Temple with a Stray Fairy chest that normally has Black Boes can instead become enemies that respawn constantly, such as Deku Babas, making it nearly impossible to clear the room and spawn the Stray Fairy chest. This can create a dud seed if the Woodfall Great Fairy holds a progression item.

**Comment by aplumafreak500** [comment]
Found an ER seed that spawns Boes in that room. They still continuously respawn, making it difficult (but not impossible) to spawn the Stray Fairy chest.

Seed: 11205068
Settings String: cf0v-2t4x-73-
(Vanilla layout seed, but still a main concern, particularly if a progression item, such as a transformation mask or a song, is present behind the Woodfall Great Fairy reward during an item randomizer seed.)

Suggestions to fix:
1: Disallow ER in either that particular room or the entire scene, whichever is easier.
2: Lock possible randomized enemies to those that do not respawn. (Note that certain enemies, such as Boes, have a setting for them not to respawn.)
3: Move the chest spawn to the flag for that room's torches, and change the door those torches are set to in vanilla from a barred door to a normal door.

**Comment by darkychao** [comment]
Enemy Randomizer is broke as hell, and this isn't the only problem with it.

Double Magic isn't randomized, anyway. The only Great Fairy reward that is is GFS

**Comment by zmarotrix** [comment]
Enemizer is a feature added by Deathbasket in the original build of the randomizer. Rather than remove it completely, we decided to simply mark it as beta and leave it as is until we decide to take the time to update it. This is not extremely high on our list of priorities. 

This is a known issue with enemizer and will be addressed once we get around to actually updating it. Thank you for your feedback.

**Comment by ZoeyZolotova** [comment]
With great fairy rewards randomized in 1.8, this issue has been fixed by preventing Boes from being randomized in WFT.
