### ISSUE TITLE
Issue with randomizer

### ISSUE THREAD

**Issue by aliensendra** [ZoeyZolotova/mm-rando#76]
Once I downloaded the updated version I got an error can’t figure out why 
![704E3115-1EB8-4C6A-A232-9CF6896A7EE9](https://user-images.githubusercontent.com/56228526/66271558-6c520e00-e82d-11e9-8c52-2204a8fa2fb2.jpeg)

**Comment by ZoeyZolotova** [comment]
Please provide some information about what you were doing when the error occurred.

**Comment by aliensendra** [comment]
I was trying to make a new randomizer to play. Once I hit randomize it showed the green at the bottom and then stopped and this error popped up.

**Comment by aliensendra** [comment]
Any idea what I should do?

**Comment by ZoeyZolotova** [comment]
Since this is a support issue, you should probably ask in the help channel on discord.
